require 'pry'
require 'nokogiri'
require 'open-uri'

require_relative '../lib/cryptie/cli'
require_relative '../lib/cryptie/scraper'
require_relative '../lib/cryptie/coin'
require_relative '../lib/cryptie/order'
require_relative '../lib/cryptie/person'
require_relative '../lib/cryptie/account'
